{{- if .Values.scheduler.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "koptimize.fullname" . }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: koptimize
      plugins:
        filter:
          enabled:
          - name: "sample"
{{- end }}