apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbird-management.fullname" . }}
  labels:
    {{- include "netbird-management.labels" . | nindent 4 }}
data:
  management.tmpl.json: |-
    {{- .Files.Get "management.tmpl.json" | nindent 4 }}
