---
name: markdownlint

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
    paths:
      - "**.md"

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install mardownlint
        run: npm install -g markdownlint-cli@0.33.0

      - name: Execute markdownlint
        run: markdownlint **/*.md
